apiVersion: v1
kind: Service
metadata:
  name: geth-service-udp
spec:
  selector:
    app: geth
  ports:
    - name: discovery
      protocol: UDP
      port: 30303
      targetPort: 30303
  type: LoadBalancer
