apiVersion: v1
kind: Service
metadata:
  name: geth-service
spec:
  selector:
    app: geth
  ports:
  - name: json-rpc
    protocol: TCP
    port: 8545
    targetPort: 8545
  - name: p2p
    protocol: TCP
    port: 30303
    targetPort: 30303
  type: LoadBalancer
