[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:geth]
command=/usr/local/bin/geth --http --http.corsdomain="https://remix.ethereum.org" --http.api web3,eth,debug,personal,net --vmdebug --datadir geth_node --dev --http.port 8545
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autostart=true
autorestart=false

[program:main]
command=/main
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autostart=true
autorestart=true