apiVersion: v1
kind: Secret
metadata:
  name: faucet-backend-secret
type: Opaque
data:
  JWT_SECRET: OTY4Njg4NTRmNGFlZGE5ZmI3MzNiMGRmZjE1ZjA4YzdjZGQwNGIxYWFkYzI3ZjBjZjhlMDdjMDBkZGY4YTY2MA==
  DSN: aG9zdD0zNS4xODQuMTE5LjE4MiB1c2VyPWdvcm0gcGFzc3dvcmQ9TDdDSmVYVEJJdVpfdFNEcE12USFQciBkYm5hbWU9c21hcnRjaGFpbiBzc2xtb2RlPWRpc2FibGU=
